### ISSUE TITLE
Allow filter params by RegExp

### ISSUE THREAD

**Issue by v-kolesnikov** [adam12/roda-enhanced_logger#10]
Hi!

I've noticed there is no way to filter params by regexp since mapping this config option to strings.

https://github.com/adam12/roda-enhanced_logger/blob/ad1a91f68c2ed7e0be5162b4e08568d11e84a3c4/lib/roda/plugins/enhanced_logger.rb#L52

At the same time TTY::Logger [supports](https://github.com/piotrmurach/tty-logger#242-filters) filtering by regexp.

**Comment by adam12** [comment]
Seems reasonable. I don't remember why I forced everything `to_s` originally, but I feel like it was a bug workaround.

Did you want to submit a PR?

**Comment by v-kolesnikov** [comment]
> Did you want to submit a PR?

Yes, i'll do.
Thanks!
