### ISSUE TITLE
roda/plugins/enhanced_logger.rb:53:in `configure': undefined method `Pathname' for Kernel:Module (NoMethodError)

### ISSUE THREAD

**Issue by wgq91here** [adam12/roda-enhanced_logger#2]
In Windows 10, Ruby 2.6.66 Or Jruby2.5 . Both this error?

And instance.rb(58) Pathname undeinfed method.

Why?

**Comment by wgq91here** [comment]
In Mac & Linux. Not found this issue.

**Comment by adam12** [comment]
Thanks for the report. Investigating.

**Comment by adam12** [comment]
I wasn't able to reproduce this, but I've added a require for `pathname`. Can you see if `master` fixes this for you?

**Comment by zzeniou86** [comment]
@adam12 I had the same problem:
```
/gems/3.0.0/gems/roda-enhanced_logger-0.3.0/lib/roda/plugins/enhanced_logger.rb:53:in `configure': undefined method `Pathname' for Roda::RodaPlugins::EnhancedLogger:Module (NoMethodError)
```

and adding `require "pathname"` fixes it!

It will be good if we have a release with this fix :)

**Comment by adam12** [comment]
> It will be good if we have a release with this fix :)

Done! v0.4.0 released.
