### ISSUE TITLE
Is it possible to log the timestamp of the request?

### ISSUE THREAD

**Issue by abhijitnandy** [adam12/roda-enhanced_logger#4]
I looked through the docs but couldn't find it. I'd like to add a timestamp at the beginning of the requiest line. Something like -
`[2020-11-30 12:01:45] ... <request details> ...`

Is it possible to do something like this?

**Comment by adam12** [comment]
Technically you can pass the `:log_time => true` option when configuring the plugin, but I double checked this and it's currently broken when being passed to the logger.

I'll look at shipping a fix for this in the next few days.

**Comment by abhijitnandy** [comment]
Thank you!

**Comment by adam12** [comment]
Fixed in be5a7bffcac06c3d7c1b15ec8a1b24dac2cb754a
